package jsonplan

import (
	"encoding/json"
	"fmt"
)

// Parser is designed to unmarshal plan json file generated by
// terraform show command.
// Details could be found: https://www.terraform.io/cli/commands/show
type Parser interface {
	Parse(raw []byte) (*Plan, error)
}

// NewParser is used as Parser constructor.
func NewParser() Parser {
	return &parser{}
}

// parser is a private implementation for Parser interface.
type parser struct {
}

// Parse is used to parse raw json bytes into Plan object.
// Note this method will fail when:
// 1. invalid raw json bytes;
// 2. the decoded format json is different from fixed version, which is FormatVersion
func (p parser) Parse(raw []byte) (*Plan, error) {
	plan := NewPlan()

	err := json.Unmarshal(raw, plan)
	if err != nil {
		return nil, err
	}

	if plan.FormatVersion != FormatVersion {
		return nil, fmt.Errorf("unsupported plan json version [%s]", plan.FormatVersion)
	}

	return plan, nil
}
